# Generated by Django 4.0.3 on 2022-03-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TL', 'Member'), ('TL', 'Leader')], default='TL', max_length=100),
        ),
    ]
