# Generated by Django 4.0.3 on 2022-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_team_team_leader_alter_task_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Under Review', 'Under Revieww'), ('Done', 'Done')], default='Assigned', max_length=20),
        ),
    ]
