# Generated by Django 4.0.3 on 2022-03-13 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_end_date_task_start_date_taskupdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 11, 15, 35, 848712)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 11, 15, 35, 848679)),
        ),
    ]
