# Generated by Django 4.0.3 on 2022-03-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_task_end_date_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TM', 'Member'), ('TL', 'Leader')], default='TM', max_length=100),
        ),
    ]
