# Generated by Django 4.0.3 on 2022-03-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='Default Name', max_length=250),
        ),
    ]
